services:
  nav2:
    image: nav2
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - pib-network
    volumes:
      - ./config:/config:ro
    privileged: true
#    restart: always
    init: true
    command: "ros2 launch nav2_bringup bringup_launch.py params_file:=/config/parameters/nav2_params.yaml"
#    command: sleep 1d

networks:
  pib-network:
    driver: bridge
