services:
  drive:
    image: drive
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - pib-network
    volumes:
      - /dev:/dev
      - ./config:/config:ro
    privileged: true
    restart: always
    command: ros2 launch /config/drive.launch.py
    # command: sleep 1d
