services:
  examples:
    image: examples
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config:/config:ro
    privileged: true

    command: ros2 launch /config/examples.launch.py
    # command: sleep 1d
