FROM georg-ros:humble

SHELL ["/bin/bash", "-c"]

WORKDIR /ws


# todo make this work over rosdep
# Q: is there a way to add rosdep dependencies without a ros package
RUN apt-get update # && apt-get install --no-install-recommends -y \

# change this variable to trick docker cache into rebuilding
ENV REBUILD=1

COPY ./pib_action_template /ws/pib_action_template
COPY ./pib_topic_template /ws/pib_topic_template

RUN rosdep install --from-paths . --ignore-src -r -y && \
    rm -rf /var/lib/apt/lists/*

RUN /bin/bash -c "\
    source /opt/ros/humble/setup.bash && \
    colcon build --symlink-install \
    "

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
