FROM georg-ros:jazzy

SHELL ["/bin/bash", "-c"]

WORKDIR /ws


# todo make this work over rosdep
# Q: is there a way to add rosdep dependencies without a ros package
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-pip \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*



# change this variable to trick docker cache into rebuilding
ENV REBUILD=1

COPY ./pib_action_template /ws/pib_action_template
COPY ./pib_topic_template /ws/pib_topic_template

RUN rosdep install --from-paths . --ignore-src -r -y && \
    rm -rf /var/lib/apt/lists/*

RUN /bin/bash -c "\
    source /opt/ros/jazzy/setup.bash && \
    colcon build --symlink-install \
    "

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
