services:
  tutorial:
    image: tutorial
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config:/config:ro
    privileged: true
    init: true
    command: 'ros2 launch /config/pubsub.launch.py'
