[Appearance]
color_scheme_path=/root/.config/qt5ct/colors/gruvbox-light.conf
custom_palette=true

[Fonts]
fixed=@Variant(\0\0\0@\0\0\0\x12\0\x43\0o\0m\0\x66\0o\0r\0t\0\x61\0\x61@\"\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0K\x10)
general=@Variant(\0\0\0@\0\0\0\x12\0\x43\0o\0m\0\x66\0o\0r\0t\0\x61\0\x61@\"\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0K\x10)
